<span style="font-size:28pt; font-weight: bold;">Default Risk Analysis Report</span>

# Table of Contents <a id='contents'></a>

1. [Initialization](#Initialization)
   - [Introduction](#Introduction)
   - [Loading Data](#Loadingh-Data)
   

2. [Data Preparation](#Data-Preparation)


3. [Data Transformation](#Data-Transformation)
   - [education Column](#education-Column)
   - [children Column](#children-Column)
   - [days_employed Column](#days_employed-Column)
   - [dob_years Column](#dob_year-Column)
   - [family_status Column](#family_status-Column)
   - [gender_Column](#gender-Column)
   - [income_type Column](#income_type-Column)
   - [Duplicates](#Duplicates)


4. [Missing Numerical Values](#Missing-Numerical-Values)
   - [total_income Column](#total_income-Column)
   - [days_employed Column](#days_employed-Column)
   

5. [Data Categorization](#Data-Categorization)
   - [purpose_Column](#purpose_Column)
   - [total_income Column](#total_income-Column)


6. [Hypotheses](#Hypotheses)
   - [Children and Loan Default](#Children-and-Loan-Default)
   - [Family Status and Loan Default](#Family-Status-and-Loan-Default)
   - [Loan Purpose and Loan Default](#Loan-Purpose-and-Loan-Default)


7. [Findings and Conclusions](#Findings-and-Conclusions)

## Initialization

### Introduction

This report is prepared for the credit division of a bank, aiming to assess how a customer's marital status and number of dependents influence the likelihood of loan default. The bank already holds some preliminary data on customer creditworthiness, which will be further analyzed in this report.

This report will be taken into account when developing **credit assessments** for prospective customers. **Credit assessments** are used to evaluate the ability of potential borrowers to repay their loans.

The following hypotheses will be tested:

1. Is there a relationship between having children and the probability of loan default?    

2. Is there a relationship between marital status and the probability of loan default?   

3. Is there a relationship between income level and the probability of loan default?    

4. How do different loan purposes affect the probability of loan default?    

### Loading Data

In [124]:
import pandas as pd

df = pd.read_csv('/datasets/credit_scoring_eng.csv')

In [125]:
df = pd.read_csv('/datasets/credit_scoring_eng.csv') # Load Dataset
df # Preview Dataset

children  days_employed  dob_years            education  education_id  \
0             1   -8437.673028         42    bachelor's degree             0   
1             1   -4024.803754         36  secondary education             1   
2             0   -5623.422610         33  Secondary Education             1   
3             3   -4124.747207         32  secondary education             1   
4             0  340266.072047         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1   -4529.316663         43  secondary education             1   
21521         0  343937.404131         67  secondary education             1   
21522         1   -2113.346888         38  secondary education             1   
21523         3   -3112.481705         38  secondary education             1   
21524         2   -1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose  
0         40620.102    purchase of the house  
1         17932.802             car purchase  
2         23341.752    purchase of the house  
3         42820.568  supplementary education  
4         25378.572        to have a wedding  
...             ...                      ...  
21520     35966.698     housing transactions  
21521     24959.969        purchase of a car  
21522     14347.610                 property  
21523     39054.888        buying my own car  
21524     13127.587             to buy a car  

[21525 rows x 12 columns]

In [126]:
df

children  days_employed  dob_years            education  education_id  \
0             1   -8437.673028         42    bachelor's degree             0   
1             1   -4024.803754         36  secondary education             1   
2             0   -5623.422610         33  Secondary Education             1   
3             3   -4124.747207         32  secondary education             1   
4             0  340266.072047         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1   -4529.316663         43  secondary education             1   
21521         0  343937.404131         67  secondary education             1   
21522         1   -2113.346888         38  secondary education             1   
21523         3   -3112.481705         38  secondary education             1   
21524         2   -1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose  
0         40620.102    purchase of the house  
1         17932.802             car purchase  
2         23341.752    purchase of the house  
3         42820.568  supplementary education  
4         25378.572        to have a wedding  
...             ...                      ...  
21520     35966.698     housing transactions  
21521     24959.969        purchase of a car  
21522     14347.610                 property  
21523     39054.888        buying my own car  
21524     13127.587             to buy a car  

[21525 rows x 12 columns]

[Back to Contents](#contents)

## Data Preparation

### Description

**Data description:**
- `children` - number of children in the family
- `days_employed` - customer’s work experience in days
- `dob_years` - customer’s age in years
- `education` - customer’s education level
- `education_id` - identifier for customer’s education level
- `family_status` - marital status
- `family_status_id` - identifier for customer’s marital status
- `gender` - customer’s gender
- `income_type` - type of employment
- `debt` - whether the customer has defaulted on a loan
- `total_income` - monthly income
- `purpose` - purpose of the loan

In [127]:
# number of rows and columns in dataset
df.shape

(21525, 12)

Dataset consists of 21.525 rows and 12 columns

In [128]:
# first 10 rows in dataset
df.head(10)

children  days_employed  dob_years            education  education_id  \
0         1   -8437.673028         42    bachelor's degree             0   
1         1   -4024.803754         36  secondary education             1   
2         0   -5623.422610         33  Secondary Education             1   
3         3   -4124.747207         32  secondary education             1   
4         0  340266.072047         53  secondary education             1   
5         0    -926.185831         27    bachelor's degree             0   
6         0   -2879.202052         43    bachelor's degree             0   
7         0    -152.779569         50  SECONDARY EDUCATION             1   
8         2   -6929.865299         35    BACHELOR'S DEGREE             0   
9         0   -2188.756445         41  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   
5  civil partnership                 1      M    business     0     40922.170   
6            married                 0      F    business     0     38484.156   
7            married                 0      M    employee     0     21731.829   
8  civil partnership                 1      F    employee     0     15337.093   
9            married                 0      M    employee     0     23108.150   

                               purpose  
0                purchase of the house  
1                         car purchase  
2                purchase of the house  
3              supplementary education  
4                    to have a wedding  
5                purchase of the house  
6                 housing transactions  
7                            education  
8                     having a wedding  
9  purchase of the house for my family

Several rows in `days_employed` column show negative value. According to the data description (customer’s work experience in days), this column should only have positive value. 

In [129]:
# dataset general info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


There are missing values in column `days_employed` and `total_income`, with identical count.

### Missing Values

In [130]:
# filter table to show rows with missing values in column days_employed
df[df['days_employed'].isna()]

children  days_employed  dob_years            education  education_id  \
12            0            NaN         65  secondary education             1   
26            0            NaN         41  secondary education             1   
29            0            NaN         63  secondary education             1   
41            0            NaN         50  secondary education             1   
55            0            NaN         54  secondary education             1   
...         ...            ...        ...                  ...           ...   
21489         2            NaN         47  Secondary Education             1   
21495         1            NaN         50  secondary education             1   
21497         0            NaN         48    BACHELOR'S DEGREE             0   
21502         1            NaN         42  secondary education             1   
21510         2            NaN         28  secondary education             1   

           family_status  family_status_id gender    income_type  debt  \
12     civil partnership                 1      M        retiree     0   
26               married                 0      M  civil servant     0   
29             unmarried                 4      F        retiree     0   
41               married                 0      F  civil servant     0   
55     civil partnership                 1      F        retiree     1   
...                  ...               ...    ...            ...   ...   
21489            married                 0      M       business     0   
21495  civil partnership                 1      F       employee     0   
21497            married                 0      F       business     0   
21502            married                 0      F       employee     0   
21510            married                 0      F       employee     0   

       total_income                   purpose  
12              NaN         to have a wedding  
26              NaN                 education  
29              NaN    building a real estate  
41              NaN  second-hand car purchase  
55              NaN         to have a wedding  
...             ...                       ...  
21489           NaN         purchase of a car  
21495           NaN          wedding ceremony  
21497           NaN       building a property  
21502           NaN    building a real estate  
21510           NaN              car purchase  

[2174 rows x 12 columns]

The number of missing values in the `days_employed` column is identical to the number of missing values in the `total_income` column. A preliminary assumption is that individuals in rows with missing values belong to employment statuses (such as student, unemployed, or retiree) that do not generate income, making it impossible to fill in the `total_income` column. However, further investigation is needed to determine if this assumption holds true.

To test the hypothesis that missing values in the `days_employed` and `total_income` columns are influenced by employment status (e.g., unemployed, retiree, student), the `income_type` column will be used as a condition to filter the data.

In [131]:
# apply missing values in 'days_employed' and 'total_income' as condition
# to filter table
df_null = df[(df['days_employed'].isnull()) & (df['total_income'].isnull())]

# show number of rows from filtered table
df_null.shape

(2174, 12)

There are 2.174 rows with missing values in column `days_employed` and `total_income`.

In [132]:
# percentage of missing values
total_entries = len(df)
missing_values_count = df['days_employed'].isna().sum()
percentage_missing = (missing_values_count / total_entries)

print(f'Percentage of missing values: {percentage_missing:.2%}')

Percentage of missing values: 10.10%


**Preliminary Conclusion:**

The results show that the missing values in the `days_employed` and `total_income` columns indeed appear in the exact same rows across all categories of the `income_type` column. However, the distribution does not align with the initial assumption that missing values would be concentrated in income types such as unemployed, retiree, or student. While there are some missing values in the **retiree** category, there are none in the **student** and **unemployed** categories. Instead, the missing values are distributed across income types like business, civil servant, employee, and entrepreneur.

The percentage of missing values compared to the entire dataset is **10.1%**. Since both `days_employed` and `total_income` are quantitative values, neglecting them would significantly impact further calculations in the data analysis process.

It appears that employment type is **not a factor** influencing the pattern of missing values.

In [133]:
# first 10 rows of table with missing values in column days_employed
df_null.head(10)

children  days_employed  dob_years            education  education_id  \
12         0            NaN         65  secondary education             1   
26         0            NaN         41  secondary education             1   
29         0            NaN         63  secondary education             1   
41         0            NaN         50  secondary education             1   
55         0            NaN         54  secondary education             1   
65         0            NaN         21  secondary education             1   
67         0            NaN         52    bachelor's degree             0   
72         1            NaN         32    bachelor's degree             0   
82         2            NaN         50    bachelor's degree             0   
83         0            NaN         52  secondary education             1   

        family_status  family_status_id gender    income_type  debt  \
12  civil partnership                 1      M        retiree     0   
26            married                 0      M  civil servant     0   
29          unmarried                 4      F        retiree     0   
41            married                 0      F  civil servant     0   
55  civil partnership                 1      F        retiree     1   
65          unmarried                 4      M       business     0   
67            married                 0      F        retiree     0   
72            married                 0      M  civil servant     0   
82            married                 0      F       employee     0   
83            married                 0      M       employee     0   

    total_income                                   purpose  
12           NaN                         to have a wedding  
26           NaN                                 education  
29           NaN                    building a real estate  
41           NaN                  second-hand car purchase  
55           NaN                         to have a wedding  
65           NaN  transactions with commercial real estate  
67           NaN       purchase of the house for my family  
72           NaN  transactions with commercial real estate  
82           NaN                                   housing  
83           NaN                                   housing

In [134]:
# distribution of data with missing values in column 'total_income'
missing_total_income = df.loc[df['total_income'].isnull()]
missing_total_income.isnull().sum()

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

Rows with missing values (NaN) in the `days_employed` column also have missing values in the `total_income` column.

**A possible explanation for these missing values** is that the data collection form or questionnaire may have provided an option for customers to leave the fields for work experience and total income blank. This would allow customers, regardless of their specific criteria, to omit information in both columns.

To confirm this, further filtering based on other categorical columns is necessary.

In [135]:
# check distribution in dataset
# column 'children'
children_null_count = df_null["children"].value_counts()
children_null_percent = df_null["children"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : children_null_percent, "count" : children_null_count}).rename_axis("unique")


percent%  count
unique                
 0       66.19%   1439
 1       21.85%    475
 2        9.38%    204
 3        1.66%     36
 20       0.41%      9
 4        0.32%      7
-1        0.14%      3
 5        0.05%      1

In [136]:
# column 'education'
education_null_count = df_null["education"].value_counts()
education_null_percent = df_null["education"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : education_null_percent, "count" : education_null_count}).rename_axis("unique")

percent%  count
unique                             
secondary education   64.77%   1408
bachelor's degree     22.82%    496
SECONDARY EDUCATION    3.08%     67
Secondary Education    2.99%     65
some college           2.53%     55
Bachelor's Degree      1.15%     25
BACHELOR'S DEGREE      1.06%     23
primary education      0.87%     19
Some College           0.32%      7
SOME COLLEGE           0.32%      7
Primary Education      0.05%      1
PRIMARY EDUCATION      0.05%      1

In [137]:
#Memeriksa distribusi di kolom 'education_id'
education_id_null_count = df_null["education_id"].value_counts()
education_id_null_percent = df_null["education_id"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : education_id_null_percent, "count" : education_id_null_count}).rename_axis("unique")

percent%  count
unique                
1        70.84%   1540
0        25.02%    544
2         3.17%     69
3         0.97%     21

In [138]:
# columnn 'family_status'
family_status_null_count = df_null["family_status"].value_counts()
family_status_null_percent = df_null["family_status"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : family_status_null_percent, "count" : family_status_null_count}).rename_axis("unique")

percent%  count
unique                           
married              56.9%   1237
civil partnership   20.33%    442
unmarried           13.25%    288
divorced             5.15%    112
widow / widower      4.37%     95

In [139]:
# column 'gender'
gender_null_count = df_null["gender"].value_counts()
gender_null_percent = df_null["gender"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : gender_null_percent, "count" : gender_null_count}).rename_axis("unique")

percent%  count
unique                
F        68.26%   1484
M        31.74%    690

In [140]:
#column 'debt'
debt_null_count = df_null["debt"].value_counts()
debt_null_percent = df_null["debt"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : debt_null_percent, "count" : debt_null_count}).rename_axis("unique")

percent%  count
unique                
0        92.18%   2004
1         7.82%    170

In [141]:
#column 'purpose'
purpose_null_count = df_null["purpose"].value_counts()
purpose_null_percent = df_null["purpose"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : purpose_null_percent, "count" : purpose_null_count}).rename_axis("unique")

percent%  count
unique                                                  
having a wedding                            4.23%     92
to have a wedding                           3.73%     81
wedding ceremony                             3.5%     76
construction of own property                3.45%     75
housing transactions                         3.4%     74
buy real estate                             3.31%     72
purchase of the house for my family         3.27%     71
transactions with my real estate            3.27%     71
housing renovation                          3.22%     70
transactions with commercial real estate    3.22%     70
buy commercial real estate                  3.08%     67
buying property for renting out             2.99%     65
property                                    2.85%     62
buy residential real estate                 2.81%     61
real estate transactions                    2.81%     61
housing                                     2.76%     60
building a property                         2.71%     59
cars                                        2.62%     57
going to university                         2.58%     56
to become educated                          2.53%     55
second-hand car purchase                    2.48%     54
buying my own car                           2.44%     53
to own a car                                2.39%     52
purchase of the house                       2.39%     52
to get a supplementary education            2.35%     51
getting an education                         2.3%     50
supplementary education                     2.21%     48
profile education                           2.16%     47
purchase of a car                           2.12%     46
building a real estate                      2.12%     46
purchase of my own house                    2.12%     46
car purchase                                1.98%     43
buying a second-hand car                    1.93%     42
education                                   1.93%     42
car                                         1.89%     41
university education                        1.84%     40
getting higher education                    1.66%     36
to buy a car                                1.38%     30

**Preliminary Conclusion**

The rows with missing values (null) in the `days_employed` and `total_income` columns are distributed across all categories in six other columns. This distribution does not reveal any significant patterns. Therefore, factors such as the number of children, education level, family status, gender, credit default history, and loan purpose do not appear to influence the occurrence of these missing values.

The following is to learn possible factor and other patterns that may have caused missing values

In [142]:
# column 'education_id'
education_id_count = df["education_id"].value_counts()
education_id_percent = df["education_id"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : education_id_percent, "count" : education_id_count}).rename_axis("unique")

percent%  count
unique                
1        70.77%  15233
0        24.44%   5260
2         3.46%    744
3         1.31%    282
4         0.03%      6

In [143]:
# column 'children'
children_count = df["children"].value_counts()
children_percent = df["children"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : children_percent, "count" : children_count}).rename_axis("unique")

percent%  count
unique                
 0       65.73%  14149
 1       22.38%   4818
 2        9.55%   2055
 3        1.53%    330
 20       0.35%     76
-1        0.22%     47
 4        0.19%     41
 5        0.04%      9

In [144]:
# column 'education'
education_count = df["education"].value_counts()
education_percent = df["education"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : education_percent, "count" : education_count}).rename_axis("unique")

percent%  count
unique                             
secondary education   63.88%  13750
bachelor's degree     21.92%   4718
SECONDARY EDUCATION    3.59%    772
Secondary Education     3.3%    711
some college            3.1%    668
BACHELOR'S DEGREE      1.27%    274
Bachelor's Degree      1.25%    268
primary education      1.16%    250
Some College           0.22%     47
SOME COLLEGE           0.13%     29
PRIMARY EDUCATION      0.08%     17
Primary Education      0.07%     15
graduate degree        0.02%      4
GRADUATE DEGREE         0.0%      1
Graduate Degree         0.0%      1

In [145]:
# column 'family_status'
family_status_count = df["family_status"].value_counts()
family_status_percent = df["family_status"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : family_status_percent, "count" : family_status_count}).rename_axis("unique")

percent%  count
unique                           
married             57.51%  12380
civil partnership   19.41%   4177
unmarried           13.07%   2813
divorced             5.55%   1195
widow / widower      4.46%    960

In [146]:
# column 'gender'
gender_count = df["gender"].value_counts()
gender_percent = df["gender"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : gender_percent, "count" : gender_count}).rename_axis("unique")

percent%  count
unique                
F        66.14%  14236
M        33.86%   7288
XNA        0.0%      1

In [147]:
# column 'debt'
debt_count = df["debt"].value_counts()
debt_percent = df["debt"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : debt_percent, "count" : debt_count}).rename_axis("unique")

percent%  count
unique                
0        91.91%  19784
1         8.09%   1741

In [148]:
# column 'purpose'
purpose_count = df["purpose"].value_counts()
purpose_percent = df["purpose"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : purpose_percent, "count" : purpose_count}).rename_axis("unique")

percent%  count
unique                                                  
wedding ceremony                             3.7%    797
having a wedding                            3.61%    777
to have a wedding                            3.6%    774
real estate transactions                    3.14%    676
buy commercial real estate                  3.08%    664
housing transactions                        3.03%    653
buying property for renting out             3.03%    653
transactions with commercial real estate    3.02%    651
purchase of the house                       3.01%    647
housing                                     3.01%    647
purchase of the house for my family         2.98%    641
construction of own property                2.95%    635
property                                    2.95%    634
transactions with my real estate            2.93%    630
building a real estate                      2.91%    626
buy real estate                              2.9%    624
purchase of my own house                    2.88%    620
building a property                         2.88%    620
housing renovation                          2.84%    612
buy residential real estate                 2.82%    607
buying my own car                           2.35%    505
going to university                          2.3%    496
car                                          2.3%    495
second-hand car purchase                    2.27%    489
to own a car                                2.23%    480
buying a second-hand car                    2.23%    479
cars                                        2.22%    478
to buy a car                                2.19%    472
car purchase                                2.15%    462
supplementary education                     2.15%    462
purchase of a car                           2.11%    455
university education                         2.1%    453
education                                   2.08%    447
to get a supplementary education            2.08%    447
getting an education                        2.06%    443
profile education                           2.03%    436
getting higher education                    1.98%    426
to become educated                          1.91%    412

**Preliminary Conclusion**

There is still no significant pattern when comparing the percentage of each group from every column in the original dataset (df) with the dataset containing only null values (df_null).

In [149]:
# checking distribution on rows with non-null values on column 'days_employed' and 'total_income'
df_not_null = df[~(df['days_employed'].isnull()) & ~(df['total_income'].isnull())]
df_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19351 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          19351 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         19351 non-null  int64  
 3   education         19351 non-null  object 
 4   education_id      19351 non-null  int64  
 5   family_status     19351 non-null  object 
 6   family_status_id  19351 non-null  int64  
 7   gender            19351 non-null  object 
 8   income_type       19351 non-null  object 
 9   debt              19351 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           19351 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 1.9+ MB


In [150]:
# column 'children'
children_notnull_count = df_not_null["children"].value_counts()
children_notnull_percent = df_not_null["children"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : children_notnull_percent, "count" : children_notnull_count}).rename_axis("unique")

percent%  count
unique                
 0       65.68%  12710
 1       22.44%   4343
 2        9.57%   1851
 3        1.52%    294
 20       0.35%     67
-1        0.23%     44
 4        0.18%     34
 5        0.04%      8

In [151]:
# column 'education'
education_notnull_count = df_not_null["education"].value_counts()
education_notnull_percent = df_not_null["education"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : education_notnull_percent, "count" : education_notnull_count}).rename_axis("unique")

percent%  count
unique                             
secondary education   63.78%  12342
bachelor's degree     21.82%   4222
SECONDARY EDUCATION    3.64%    705
Secondary Education    3.34%    646
some college           3.17%    613
BACHELOR'S DEGREE       1.3%    251
Bachelor's Degree      1.26%    243
primary education      1.19%    231
Some College           0.21%     40
SOME COLLEGE           0.11%     22
PRIMARY EDUCATION      0.08%     16
Primary Education      0.07%     14
graduate degree        0.02%      4
GRADUATE DEGREE        0.01%      1
Graduate Degree        0.01%      1

In [152]:
# column 'education_id'
education_id_notnull_count = df_not_null["education_id"].value_counts()
education_id_notnull_percent = df_not_null["education_id"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : education_id_notnull_percent, "count" : education_id_notnull_count}).rename_axis("unique")

percent%  count
unique                
1        70.76%  13693
0        24.37%   4716
2         3.49%    675
3         1.35%    261
4         0.03%      6

In [153]:
# column 'family_status'
family_status_notnull_count = df_not_null["family_status"].value_counts()
family_status_notnull_percent = df_not_null["family_status"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : family_status_notnull_percent, "count" : family_status_notnull_count}).rename_axis("unique")

percent%  count
unique                           
married             57.58%  11143
civil partnership    19.3%   3735
unmarried           13.05%   2525
divorced              5.6%   1083
widow / widower      4.47%    865

In [154]:
# column 'gender'
gender_notnull_count = df_not_null["gender"].value_counts()
gender_notnull_percent = df_not_null["gender"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : gender_notnull_percent, "count" : gender_notnull_count}).rename_axis("unique")

percent%  count
unique                
F         65.9%  12752
M         34.1%   6598
XNA       0.01%      1

In [155]:
# column 'debt'
debt_notnull_count = df_not_null["debt"].value_counts()
debt_notnull_percent = df_not_null["debt"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : debt_notnull_percent, "count" : debt_notnull_count}).rename_axis("unique")

percent%  count
unique                
0        91.88%  17780
1         8.12%   1571

In [156]:
# column 'purpose'
purpose_notnull_count = df_not_null["purpose"].value_counts()
purpose_notnull_percent = df_not_null["purpose"].value_counts(normalize=True).mul(100).round(2).astype(str)+"%"
pd.DataFrame(data={"percent%" : purpose_notnull_percent, "count" : purpose_notnull_count}).rename_axis("unique")

percent%  count
unique                                                  
wedding ceremony                            3.73%    721
to have a wedding                           3.58%    693
having a wedding                            3.54%    685
real estate transactions                    3.18%    615
buy commercial real estate                  3.09%    597
purchase of the house                       3.07%    595
buying property for renting out             3.04%    588
housing                                     3.03%    587
transactions with commercial real estate     3.0%    581
building a real estate                       3.0%    580
housing transactions                        2.99%    579
purchase of my own house                    2.97%    574
property                                    2.96%    572
purchase of the house for my family         2.95%    570
building a property                          2.9%    561
construction of own property                2.89%    560
transactions with my real estate            2.89%    559
buy real estate                             2.85%    552
buy residential real estate                 2.82%    546
housing renovation                           2.8%    542
car                                         2.35%    454
buying my own car                           2.34%    452
to buy a car                                2.28%    442
going to university                         2.27%    440
buying a second-hand car                    2.26%    437
second-hand car purchase                    2.25%    435
to own a car                                2.21%    428
cars                                        2.18%    421
car purchase                                2.17%    419
supplementary education                     2.14%    414
university education                        2.13%    413
purchase of a car                           2.11%    409
education                                   2.09%    405
to get a supplementary education            2.05%    396
getting an education                        2.03%    393
getting higher education                    2.02%    390
profile education                           2.01%    389
to become educated                          1.84%    357

**Preliminary Conclusion**

After comparing the distribution of each column across the original dataset, the dataset containing only null values, and the dataset containing only non-null values, no discernible pattern was found. The proportion of values in each category remains relatively consistent across all three datasets.

[Back to Contents](#contents)

## Data Transformation

### `education` Column

Eliminate duplicates and make necessary input corrections 

In [157]:
# check unique values in 'education' column
df['education'].unique()

array(["bachelor's degree", 'secondary education', 'Secondary Education',
       'SECONDARY EDUCATION', "BACHELOR'S DEGREE", 'some college',
       'primary education', "Bachelor's Degree", 'SOME COLLEGE',
       'Some College', 'PRIMARY EDUCATION', 'Primary Education',
       'Graduate Degree', 'GRADUATE DEGREE', 'graduate degree'],
      dtype=object)

Inconsistency in data input writing where some used all uppercase, some all lowercase, and others the mixture of lower and uppercase. 

In [158]:
# correct input into lowercase
df['education'] = df['education'].str.lower()

# show corrected data input
df['education'].unique()

array(["bachelor's degree", 'secondary education', 'some college',
       'primary education', 'graduate degree'], dtype=object)

All inputs have been corrected into all lowercase. 

In [159]:
# value counts after input correction
df['education'].value_counts()

secondary education    15233
bachelor's degree       5260
some college             744
primary education        282
graduate degree            6
Name: education, dtype: int64

**Data Transformation in the** `education` **Column**

The values in this column exhibit several variations that convey the same meaning. Some are entered in uppercase letters, while others are in lowercase. Standardization has been applied to ensure that all values are consistently displayed in **lowercase format**.

### `children` Column

In [160]:
# check unique values in column `children`
df['children'].unique()

array([ 1,  0,  3,  2, -1,  4, 20,  5])

In [161]:
df['children'].value_counts()

 0     14149
 1      4818
 2      2055
 3       330
 20       76
-1        47
 4        41
 5         9
Name: children, dtype: int64

There are 47 rows with value -1 for number of children. The following are to check further on the case:

In [162]:
df[df['children'] == -1]

children  days_employed  dob_years            education  education_id  \
291          -1   -4417.703588         46  secondary education             1   
705          -1    -902.084528         50  secondary education             1   
742          -1   -3174.456205         57  secondary education             1   
800          -1  349987.852217         54  secondary education             1   
941          -1            NaN         57  secondary education             1   
1363         -1   -1195.264956         55  secondary education             1   
1929         -1   -1461.303336         38  secondary education             1   
2073         -1   -2539.761232         42  secondary education             1   
3814         -1   -3045.290443         26  secondary education             1   
4201         -1    -901.101738         41  secondary education             1   
4402         -1  398001.302888         64  secondary education             1   
4542         -1   -1811.899756         32  secondary education             1   
5272         -1   -1143.485347         46  secondary education             1   
6013         -1   -1361.258696         46    bachelor's degree             0   
6385         -1  370215.476226         48  secondary education             1   
7190         -1   -5928.202068         34  secondary education             1   
7278         -1    -526.318451         51  secondary education             1   
7615         -1            NaN         35  secondary education             1   
7685         -1   -3237.360455         53  secondary education             1   
8229         -1   -1803.441074         54    bachelor's degree             0   
8251         -1   -3113.998449         31  secondary education             1   
8561         -1    -195.479496         31  secondary education             1   
9565         -1   -2896.629686         34    bachelor's degree             0   
9574         -1   -2710.419901         28    bachelor's degree             0   
10177        -1   -1743.604011         37  secondary education             1   
10365        -1  345774.125957         63    bachelor's degree             0   
10918        -1  340499.039342         50  secondary education             1   
11109        -1   -3438.463024         59  secondary education             1   
11268        -1   -1048.782203         30    bachelor's degree             0   
11617        -1    -370.827130         27  secondary education             1   
12304        -1   -8493.101252         61         some college             2   
13786        -1            NaN         42  secondary education             1   
14357        -1    -268.337037         23  secondary education             1   
15147        -1   -9851.184337         44  secondary education             1   
15435        -1   -3614.220232         40    bachelor's degree             0   
16129        -1    -457.861760         33  secondary education             1   
16265        -1   -2802.218127         40    bachelor's degree             0   
17095        -1   -2809.693200         34  secondary education             1   
17429        -1    -895.379738         37  secondary education             1   
17657        -1   -4571.957475         41  secondary education             1   
18219        -1   -3575.215641         33  secondary education             1   
19100        -1    -617.246968         38  secondary education             1   
19366        -1    -372.034749         43  secondary education             1   
19417        -1  350340.760224         28  secondary education             1   
20393        -1  355157.107212         69  secondary education             1   
20717        -1    -661.822321         32    bachelor's degree             0   
21140        -1   -1422.668059         44  secondary education             1   

           family_status  family_status_id gender    income_type  debt  \
291    civil partnership                 1      F       employee     0   
705              m

There are also extreme cases with number of children "20", as follow:

In [163]:
df[df['children'] == 20]

children  days_employed  dob_years            education  education_id  \
606          20    -880.221113         21  secondary education             1   
720          20    -855.595512         44  secondary education             1   
1074         20   -3310.411598         56  secondary education             1   
2510         20   -2714.161249         59    bachelor's degree             0   
2941         20   -2161.591519          0  secondary education             1   
...         ...            ...        ...                  ...           ...   
21008        20   -1240.257910         40  secondary education             1   
21325        20    -601.174883         37  secondary education             1   
21390        20            NaN         53  secondary education             1   
21404        20    -494.788448         52  secondary education             1   
21491        20    -173.954460         27  secondary education             1   

         family_status  family_status_id gender income_type  debt  \
606            married                 0      M    business     0   
720            married                 0      F    business     0   
1074           married                 0      F    employee     1   
2510   widow / widower                 2      F    employee     0   
2941           married                 0      F    employee     0   
...                ...               ...    ...         ...   ...   
21008          married                 0      F    employee     1   
21325          married                 0      F    business     0   
21390          married                 0      M    business     0   
21404          married                 0      M    business     0   
21491          married                 0      F    employee     0   

       total_income                                   purpose  
606       23253.578                     purchase of the house  
720       18079.798                           buy real estate  
1074      36722.966                      getting an education  
2510      42315.974  transactions with commercial real estate  
2941      31958.391                              to buy a car  
...             ...                                       ...  
21008     21363.842                              to own a car  
21325     16477.771                         profile education  
21390           NaN               buy residential real estate  
21404     25060.749          transactions with my real estate  
21491     24883.344                  buying a second-hand car  

[76 rows x 12 columns]

In the `children` column, there are confusing data entries, such as -1 and 20. There are 47 rows with a value of '-1' and 76 rows with a value of '20'. Upon examining the locations of these entries, their distribution does not point to any specific pattern. 

Rows containing either -1 or 20 in the 'children' column come from various categories in other columns, rather than clustering within any particular category. As a percentage, the total number of rows with values of '-1' or '20' does not exceed 1% of the overall dataset. 

However, these values are quantitative and the number of children is a significant variable for testing hypotheses. Therefore, both values need to be replaced with representative figures.

Any entry other than 0 in the `children` column will be considered as having children. The value '-1' will be replaced with '1', while the value '20', being an extreme outlier, will be replaced with the median of all values in the `children` column.

In [164]:
# data correction
median_children = df['children'].median() #calculate median value of the 'children' column
df['children'] = df['children'].replace(20, median_children) # Replace the value 20 with the calculated median
df['children'].unique() # Display the unique values in the 'children' column

array([ 1.,  0.,  3.,  2., -1.,  4.,  5.])

In [165]:
# replace value -1 with 1
df['children'] = df['children'].replace(-1, 1)
df['children'].unique()

array([1., 0., 3., 2., 4., 5.])

In [166]:
# check column `children` value counts after data correction
df['children'].value_counts()

0.0    14225
1.0     4865
2.0     2055
3.0      330
4.0       41
5.0        9
Name: children, dtype: int64

In [167]:
# change data type to integer
df['children'].astype(int)

0        1
1        1
2        0
3        3
4        0
        ..
21520    1
21521    0
21522    1
21523    3
21524    2
Name: children, Length: 21525, dtype: int64

All error inputs (resulting in negative values) and extreme values in column `children` have been replaced, and eliminated respectively. 

### `days_employed` Column

The `days_employed` column is expected to contain information on the number of days indicating the length of a customer's employment. 

However, some rows were found to have negative values in this column. It is essential to identify how many rows contain these negative values for further analysis.

In [168]:
#statistical description of column days_employed
df['days_employed'].describe()

count     19351.000000
mean      63046.497661
std      140827.311974
min      -18388.949901
25%       -2747.423625
50%       -1203.369529
75%        -291.095954
max      401755.400475
Name: days_employed, dtype: float64

The number of rows with negative values in the `days_employed` column exceeds 50% of the total entries in the dataset. The data type for this column is currently float, although the number of days should logically be represented as integers.

Additionally, there are extreme positive values in the column that, when converted to years (by dividing by 365), result in unrealistic values (e.g., 401,755 days, which equates to 1,100 years).

To address these issues, a four-step data transformation is required. 

First, all negative values will be converted to positive.

Second, extreme values that exceed a customer’s reasonable lifespan will be adjusted to reflect meaningful employment duration. Even the minimum value in the days_employed_positive variable (328,728.720605) converts to a value in years that is far too high compared to the customer’s age. Therefore, rows with values of 328,728.720605 or above in the days_employed column will be divided by 100.

Third, all missing values (NaN) will be replaced with 0.

Finally, the data type will be converted from float to integer.

In [169]:
# convert negative values
days_employed = df.loc[df['days_employed'] < 0, 'days_employed'] = df['days_employed'].abs()
days_employed.describe()

count     19351.000000
mean      66914.728907
std      139030.880527
min          24.141633
25%         927.009265
50%        2194.220567
75%        5537.882441
max      401755.400475
Name: days_employed, dtype: float64

Following the conversion of all negative values to positive, a significant disparity was observed between the lower boundary (75th percentile) and the upper boundary (maximum) within the fourth quartile. This quartile contains the outlier values. It is necessary to establish a threshold beyond which any value is deemed an outlier and requires adjustment to a more reasonable figure.

The **threshold** was calculated based on **the typical working life span**, ranging from the legal working age of 21 years to the retirement age of 65 years, which amounts to 44 years. When expressed in days, this period totals 16,060 days. Therefore, the threshold for identifying outliers is set at 16,060 days. Values exceeding this limit will be considered extreme and subject to transformation.

In [170]:
# replace extreme positive values
threshold_value = 16060
# filter rows with value equals to threshold and greater
df.loc[df['days_employed'] > threshold_value, 'days_employed'] = threshold_value
df['days_employed'].describe()

count    19351.000000
mean      4792.986876
std       5643.856455
min         24.141633
25%        927.009265
50%       2194.220567
75%       5537.882441
max      16060.000000
Name: days_employed, dtype: float64

The current maximum score in column `days_employed` is 16060, which indicates that extremely high values have been all replaced with threshold value. 

### `dob_years` Column

In [171]:
# check `dob_years` for extreme values
sorted(df['dob_years'].unique())

[0,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75]

Ages below 19 are not eligible for load application. The dataset indicates some rows have value "0". The following is to identify the number of rows with value "0" in column `dob_years`.

In [172]:
# number of rows with value 0 in dob_years
(df['dob_years'] == 0).sum()

101

There are 101 rows with a value of 0 in the `dob_years` column, which amounts to **less than 0.5%** of the total rows in the dataset. It is likely that the 0 values in this column result from missing data. While age is not a variable required for hypothesis testing, it is necessary for data categorization. Therefore, the 0 values need to be replaced with a more representative value. 

Given the absence of extreme outliers among the unique values in the `dob_years` column, the 0 values will be replaced with the **mean** value.

In [173]:
#calculate mean value of column 'dob_years'
mean_dob_years = df[df['dob_years'] != 0]['dob_years'].mean()

mean_dob_years = int(mean_dob_years) #convert to integer
print('mean value:', mean_dob_years)

mean value: 43


In [174]:
#replace 0 with mean value
df.loc[df['dob_years'] == 0, 'dob_years'] = mean_dob_years

In [175]:
# show unique values
sorted(df['dob_years'].unique())

[19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75]

There is no more 0 value in column `dob_years`, all have been replaced with 43 as the mean value. 

### `family_status` Column

In [176]:
# show unique values and counts
df['family_status'].value_counts()

married              12380
civil partnership     4177
unmarried             2813
divorced              1195
widow / widower        960
Name: family_status, dtype: int64

There is no particular problem found in column 'family_status'.

### `gender` Column

In [177]:
# show unique values and counts
df['gender'].value_counts()

F      14236
M       7288
XNA        1
Name: gender, dtype: int64

There is no explanation provided for the meaning of "XNA" in the gender column. Since it occurs in only one instance and gender is not a variable being tested in the hypothesis, the decision has been made to remove the row containing the "XNA" value.

In [178]:
# define column 'gender' to exclude all rows containing 'XNA'
df = df[df['gender'] != 'XNA']
df['gender'].value_counts()

F    14236
M     7288
Name: gender, dtype: int64

### `income_type` Column

In [179]:
# show unique values and count
df['income_type'].value_counts()

employee                       11119
business                        5084
retiree                         3856
civil servant                   1459
entrepreneur                       2
unemployed                         2
student                            1
paternity / maternity leave        1
Name: income_type, dtype: int64

There is no particular problem found in column 'income_type'

### Duplicates

In [180]:
# show total duplicates in dataset
duplicate_count = df.duplicated().sum()
duplicate_count

71

In [181]:
# eliminate explicit duplicates
df = df.drop_duplicates().reset_index(drop=True) #reset index

In [182]:
# show general information of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21453 entries, 0 to 21452
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21453 non-null  float64
 1   days_employed     19350 non-null  float64
 2   dob_years         21453 non-null  int64  
 3   education         21453 non-null  object 
 4   education_id      21453 non-null  int64  
 5   family_status     21453 non-null  object 
 6   family_status_id  21453 non-null  int64  
 7   gender            21453 non-null  object 
 8   income_type       21453 non-null  object 
 9   debt              21453 non-null  int64  
 10  total_income      19350 non-null  float64
 11  purpose           21453 non-null  object 
dtypes: float64(3), int64(4), object(5)
memory usage: 2.0+ MB


In [183]:
df.shape

(21453, 12)

Based on the adjusted dataset, several key changes were observed following the data manipulation:

The total number of entries in the dataset decreased from 21,525 to 21,454 after duplicate rows were removed. The missing values in the `days_employed` column were successfully addressed, resulting in the number of non-null values now equaling the total number of entries (21,454). Additionally, the data type for this column was changed from float to integer to better represent the values.

However, there are still 2,103 missing values in the `total_income` column that remain to be addressed.

[Back to Contents](#contents)

## Missing Numerical Values

In order to address missing values on columns that will be used in hypothesis testing, other columns in the data can be used to be made into dictionary.

Two columns have already been categorized into values that can serve as IDs: 
* customer education level (`education_id`), and 
* marital status (`family_status_id`) 

These columns can be converted into dictionaries, where `education_id` serves as the key and `education` as the value. 
Similarly, `family_status_id` can be mapped to `family_status` in a dictionary.

In [184]:
# education dictionary
dict(zip(df.education_id, df.education))

{0: "bachelor's degree",
 1: 'secondary education',
 2: 'some college',
 3: 'primary education',
 4: 'graduate degree'}

In [185]:
# family status dictionary
dict(zip(df.family_status_id, df.family_status))

{0: 'married',
 1: 'civil partnership',
 2: 'widow / widower',
 3: 'divorced',
 4: 'unmarried'}

###  `total_income` Column

The `total_income` column contains the monthly income of customers. According to the most recent dataset, there are **2,103 missing values** in this column. Since the values in this column are numerical and will affect subsequent calculations, a representative value must be determined to replace the missing data.

To gain further insight into the missing values in this column, the data will first be categorized based on age. As an initial step, a new column will be added that contains age categories.

In [186]:
# data distribution for column 'dob_years'
df['dob_years'].describe()

count    21453.000000
mean        43.474572
std         12.213068
min         19.000000
25%         33.000000
50%         43.000000
75%         53.000000
max         75.000000
Name: dob_years, dtype: float64

In [187]:
# function to categorize according to age group
def age_categorization(age):
    if age <= 20:
        category = '0-20'
    elif age > 20 and age <= 40:
        category = '20-40'
    elif age > 40 and age <= 60:
        category = '40-60'
    elif age > 60 and age <= 80:
        category = '60-80'
    else:
        category = '>80'
    return category

In [188]:
# test function
age_1 = 47
age_2 = 29
age_3 = 90

age_categorization(age_1)

'40-60'

In [189]:
age_categorization(age_2)

'20-40'

In [190]:
age_categorization(age_3)

'>80'

In [191]:
# apply function and keep result in separate column
df['age_category'] = df['dob_years'].apply(age_categorization)
df.loc[:, ['dob_years', 'age_category']].head(10) #show first 10 rows

dob_years age_category
0         42        40-60
1         36        20-40
2         33        20-40
3         32        20-40
4         53        40-60
5         27        20-40
6         43        40-60
7         50        40-60
8         35        20-40
9         41        40-60

In [192]:
# check unique values and counts in column 'age_category'
df['age_category'].value_counts()

40-60    9879
20-40    9383
60-80    2126
0-20       65
Name: age_category, dtype: int64

In [193]:
#separate dataset without missing values
nomiss_data = df.loc[~df['total_income'].isnull()]
nomiss_data.head(10) #show first 10 rows

children  days_employed  dob_years            education  education_id  \
0       1.0    8437.673028         42    bachelor's degree             0   
1       1.0    4024.803754         36  secondary education             1   
2       0.0    5623.422610         33  secondary education             1   
3       3.0    4124.747207         32  secondary education             1   
4       0.0   16060.000000         53  secondary education             1   
5       0.0     926.185831         27    bachelor's degree             0   
6       0.0    2879.202052         43    bachelor's degree             0   
7       0.0     152.779569         50  secondary education             1   
8       2.0    6929.865299         35    bachelor's degree             0   
9       0.0    2188.756445         41  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   
5  civil partnership                 1      M    business     0     40922.170   
6            married                 0      F    business     0     38484.156   
7            married                 0      M    employee     0     21731.829   
8  civil partnership                 1      F    employee     0     15337.093   
9            married                 0      M    employee     0     23108.150   

                               purpose age_category  
0                purchase of the house        40-60  
1                         car purchase        20-40  
2                purchase of the house        20-40  
3              supplementary education        20-40  
4                    to have a wedding        40-60  
5                purchase of the house        20-40  
6                 housing transactions        40-60  
7                            education        40-60  
8                     having a wedding        20-40  
9  purchase of the house for my family        40-60

In [194]:
# show average income for each age category
nomiss_data.groupby('age_category')['total_income'].mean().reset_index()

age_category  total_income
0         0-20  19586.303559
1        20-40  27421.165343
2        40-60  27034.666405
3        60-80  23057.777452

In [195]:
# show median income of each age category
nomiss_data.groupby('age_category')['total_income'].median().reset_index()

age_category  total_income
0         0-20    17257.2770
1        20-40    23972.1930
2        40-60    23219.8075
3        60-80    19637.0560

In [196]:
# data distribution of column 'total_income'
df['total_income'].describe()

count     19350.000000
mean      26787.266688
std       16475.822926
min        3306.762000
25%       16486.515250
50%       23201.873500
75%       32547.910750
max      362496.645000
Name: total_income, dtype: float64

The values in the total_income column exhibit a normal distribution, with no extreme outliers present. Therefore, the representative value chosen to replace the missing entries will be the **mean value**.

In [197]:
#mean value for each age category
mean = pd.pivot_table(data=df, columns='age_category', values='total_income', aggfunc='mean')
mean

age_category          0-20         20-40         40-60         60-80
total_income  19586.303559  27421.165343  27034.666405  23057.777452

In [198]:
# Calculating the mean value of total_income for the age range of 20-40
mean['20-40'][0]
# Method for imputing the mean into missing values by age category
df.loc[(df['age_category']=='20-40') & (df['total_income'].isnull()), 'total_income'] = mean['20-40'][0]

# looping method
for col in mean.columns:
    df.loc[(df['age_category']==col) & (df['total_income'].isnull()), 'total_income'] = mean[col][0]
    print(col)

0-20
20-40
40-60
60-80


In [199]:
# check missing values
df.isnull().sum()

children               0
days_employed       2103
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income           0
purpose                0
age_category           0
dtype: int64

In [200]:
# check value replacement in 'total_income' column
df.head()

children  days_employed  dob_years            education  education_id  \
0       1.0    8437.673028         42    bachelor's degree             0   
1       1.0    4024.803754         36  secondary education             1   
2       0.0    5623.422610         33  secondary education             1   
3       3.0    4124.747207         32  secondary education             1   
4       0.0   16060.000000         53  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   

                   purpose age_category  
0    purchase of the house        40-60  
1             car purchase        20-40  
2    purchase of the house        20-40  
3  supplementary education        20-40  
4        to have a wedding        40-60

In [201]:
# display rows with missing values in column 'total_income'
df.loc[df['total_income'].isnull()]

Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose, age_category]
Index: []

In [202]:
# check non-null count in 'total_income' column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21453 entries, 0 to 21452
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21453 non-null  float64
 1   days_employed     19350 non-null  float64
 2   dob_years         21453 non-null  int64  
 3   education         21453 non-null  object 
 4   education_id      21453 non-null  int64  
 5   family_status     21453 non-null  object 
 6   family_status_id  21453 non-null  int64  
 7   gender            21453 non-null  object 
 8   income_type       21453 non-null  object 
 9   debt              21453 non-null  int64  
 10  total_income      21453 non-null  float64
 11  purpose           21453 non-null  object 
 12  age_category      21453 non-null  object 
dtypes: float64(3), int64(4), object(6)
memory usage: 2.1+ MB


All missing values in column `total_income` have been replaced with mean values according to the age category every customer is assigned to. Now the non-null count of `total_income` is identical with the total entries in the dataset.

###  `days_employed` Column

In [203]:
# replace missing values in 'days_employed' with 0
df['days_employed'] = df['days_employed'].fillna(0)
df['days_employed'].isna().sum() #show number of rows with missing values following replacement

0

In [204]:
# round up values in 'days_employed'
df['days_employed'] = df['days_employed'].round()
df['days_employed'].describe() #show distribution

count    21453.000000
mean      4323.251853
std       5546.448568
min          0.000000
25%        622.000000
50%       1821.000000
75%       4798.000000
max      16060.000000
Name: days_employed, dtype: float64

In [205]:
# convert value type to integer
df['days_employed'] = df['days_employed'].astype(int)

In [206]:
# check entry in all columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21453 entries, 0 to 21452
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21453 non-null  float64
 1   days_employed     21453 non-null  int64  
 2   dob_years         21453 non-null  int64  
 3   education         21453 non-null  object 
 4   education_id      21453 non-null  int64  
 5   family_status     21453 non-null  object 
 6   family_status_id  21453 non-null  int64  
 7   gender            21453 non-null  object 
 8   income_type       21453 non-null  object 
 9   debt              21453 non-null  int64  
 10  total_income      21453 non-null  float64
 11  purpose           21453 non-null  object 
 12  age_category      21453 non-null  object 
dtypes: float64(2), int64(5), object(6)
memory usage: 2.1+ MB


Now column `days_employed` exhibits identical non-null counts with the total entries in dataset. 

[Back to Contents](#contents)

## Data Categorization

In hypothesis testing, data is required from the following columns:

* `children`
* `family_status`
* `total_income`
* `debt`
* `purpose`

For the `children` column, since the range of the number of children is limited (0-5), categorization is unnecessary; each number of children can serve as its own category.

The `family_status` column already has categorization established in another column, namely `family_status_id`.

In the case of the `debt` column, the values are already categorical, with 1 indicating customers who have defaulted on payments and 0 representing those who have not.

Categorization is needed for the `total_income` and `purpose` columns.

For the `total_income` categorization, the **interquartile range** of the data distribution will be examined. If the interquartile range is consistent, categorization can be performed using the **upper limits** of each quartile.

Regarding the `purpose` column, this contains categorical values with unique entries that vary widely, necessitating grouping into **several general themes based on keywords** present in the data.

### `purpose` Column

In [207]:
# show unique values and counts in 'purpose' column
df[['purpose']].value_counts()

purpose                                 
wedding ceremony                            791
having a wedding                            768
to have a wedding                           765
real estate transactions                    675
buy commercial real estate                  661
housing transactions                        652
buying property for renting out             651
transactions with commercial real estate    650
purchase of the house                       646
housing                                     646
purchase of the house for my family         638
construction of own property                635
property                                    633
transactions with my real estate            627
building a real estate                      624
buy real estate                             620
purchase of my own house                    620
building a property                         619
housing renovation                          607
buy residential real estate                 606

In [208]:
# sort unique values in alphabetical order
sorted(df['purpose'].unique())

['building a property',
 'building a real estate',
 'buy commercial real estate',
 'buy real estate',
 'buy residential real estate',
 'buying a second-hand car',
 'buying my own car',
 'buying property for renting out',
 'car',
 'car purchase',
 'cars',
 'construction of own property',
 'education',
 'getting an education',
 'getting higher education',
 'going to university',
 'having a wedding',
 'housing',
 'housing renovation',
 'housing transactions',
 'profile education',
 'property',
 'purchase of a car',
 'purchase of my own house',
 'purchase of the house',
 'purchase of the house for my family',
 'real estate transactions',
 'second-hand car purchase',
 'supplementary education',
 'to become educated',
 'to buy a car',
 'to get a supplementary education',
 'to have a wedding',
 'to own a car',
 'transactions with commercial real estate',
 'transactions with my real estate',
 'university education',
 'wedding ceremony']

The unique values in the `purpose` column can be summarized into four main themes:

* **Vehicle-related purpose:** All needs related to transportation (e.g., "car," "buying my own car").
* **Education-related purpose:** All needs associated with education (e.g., "going to university," "supplementary education").
* **Residential-related purpose:** All needs pertaining to housing, regardless of the specific use (e.g., "property," "housing renovation," "building a real estate").
* **Other purpose:** All needs that do not fall into the three categories above (e.g., "to have a wedding").

Each value in this column will be categorized into one of the following categories: 
* **vehicle**, 
* **educational**, 
* **residential**, and 
* **other**. 

Grouping will be performed based on keywords present in each unique value. 
For example, if a row in this column contains the word *"property,"* it will be categorized as **residential**. 
The results of this categorization will be stored in a new column named `purpose_category`.

In [209]:
# function to categorize purpose based on fragments of keywords
def purpose_category(purpose):
    if ('hous' in purpose) or ('property' in purpose) or ('estate' in purpose):
        category = 'residential'
        print(category)
    elif ('educat' in purpose) or ('university' in purpose) or ('estate' in purpose):
        category = 'educational'
        print(category)
    elif ('car' in purpose):
        category = 'vehicle'
        print(category)
    else:
        category = 'other'
    
    return category

purpose_1 = 'transactions with my real estate'
purpose_2 = 'to buy a car'
purpose_3 = 'wedding ceremony'

#test function
purpose_category(purpose_1)
purpose_category(purpose_2)
purpose_category(purpose_3)

residential
vehicle


'other'

In [210]:
df['purpose_category'] = df['purpose'].apply(purpose_category)

residential
vehicle
residential
educational
residential
residential
educational
residential
residential
residential
vehicle
residential
residential
residential
residential
vehicle
vehicle
residential
vehicle
vehicle
residential
residential
educational
residential
residential
residential
residential
residential
residential
residential
vehicle
vehicle
educational
educational
residential
vehicle
educational
vehicle
vehicle
educational
vehicle
residential
vehicle
vehicle
educational
residential
vehicle
educational
educational
residential
residential
educational
residential
educational
residential
vehicle
residential
educational
residential
residential
residential
residential
vehicle
residential
educational
residential
residential
vehicle
vehicle
vehicle
vehicle
vehicle
educational
residential
residential
residential
educational
residential
vehicle
residential
residential
vehicle
vehicle
residential
educational
residential
vehicle
residential
vehicle
vehicle
residential
residential
resident

vehicle
educational
educational
residential
vehicle
residential
residential
vehicle
residential
residential
educational
vehicle
residential
residential
vehicle
vehicle
vehicle
residential
educational
residential
residential
residential
residential
residential
residential
residential
residential
educational
educational
vehicle
vehicle
vehicle
residential
educational
residential
educational
vehicle
residential
educational
residential
residential
residential
residential
residential
residential
residential
residential
vehicle
residential
vehicle
educational
residential
residential
residential
vehicle
residential
educational
educational
educational
residential
residential
educational
vehicle
residential
residential
vehicle
residential
educational
residential
educational
residential
residential
residential
vehicle
residential
residential
residential
residential
residential
residential
educational
vehicle
residential
residential
residential
vehicle
residential
residential
residential
resident

In [211]:
#first 10 rows of dataset with added purpose_category column
df.head(10)

children  days_employed  dob_years            education  education_id  \
0       1.0           8438         42    bachelor's degree             0   
1       1.0           4025         36  secondary education             1   
2       0.0           5623         33  secondary education             1   
3       3.0           4125         32  secondary education             1   
4       0.0          16060         53  secondary education             1   
5       0.0            926         27    bachelor's degree             0   
6       0.0           2879         43    bachelor's degree             0   
7       0.0            153         50  secondary education             1   
8       2.0           6930         35    bachelor's degree             0   
9       0.0           2189         41  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   
5  civil partnership                 1      M    business     0     40922.170   
6            married                 0      F    business     0     38484.156   
7            married                 0      M    employee     0     21731.829   
8  civil partnership                 1      F    employee     0     15337.093   
9            married                 0      M    employee     0     23108.150   

                               purpose age_category purpose_category  
0                purchase of the house        40-60      residential  
1                         car purchase        20-40          vehicle  
2                purchase of the house        20-40      residential  
3              supplementary education        20-40      educational  
4                    to have a wedding        40-60            other  
5                purchase of the house        20-40      residential  
6                 housing transactions        40-60      residential  
7                            education        40-60      educational  
8                     having a wedding        20-40            other  
9  purchase of the house for my family        40-60      residential

### '`total_income` Column

In [212]:
# data distribution of column 'total_income'
df['total_income'].describe()

count     21453.000000
mean      26787.032509
std       15652.835766
min        3306.762000
25%       17219.352000
50%       24617.544000
75%       31327.922000
max      362496.645000
Name: total_income, dtype: float64

Based on the distribution of the data, the column exhibits a consistent interquartile range. Therefore, categorization can be performed using the upper bounds of each quartile.

Category **low**: for values less than or equal to 17,220
Category **lower middle**: for values greater than 17,220 and less than or equal to 24,618
Category **upper middle**: for values greater than 24,618 and less than or equal to 31,330
Category **high**: for values greater than 31,330

The results of this categorization will be stored in a new column named `income_category`.

In [213]:
# function to categorize income
def income_category(income):
    if income <= 17220:
        category = 'low'
        print(category)
    elif income <= 24618:
        category = 'lower middle'
        print(category)
    elif income <= 31330:
        category = 'upper middle'
        print(category)
    else:
        category = 'high'
    
    return category

income_1 = 24619
income_2 = 15652
income_3 = 31400

# test function
income_category(income_1)
income_category(income_2)
income_category(income_3)

upper middle
low


'high'

In [214]:
# apply function to column 'total_income' and store results in new column
df['income_category'] = df['total_income'].apply(income_category);

lower middle
lower middle
upper middle
lower middle
low
lower middle
lower middle
low
lower middle
lower middle
upper middle
lower middle
low
low
lower middle
lower middle
lower middle
low
upper middle
upper middle
lower middle
upper middle
lower middle
upper middle
low
low
lower middle
upper middle
upper middle
lower middle
upper middle
low
low
low
upper middle
upper middle
low
low
low
low
upper middle
lower middle
low
lower middle
upper middle
lower middle
upper middle
lower middle
upper middle
low
low
upper middle
low
low
low
lower middle
lower middle
upper middle
low
lower middle
upper middle
upper middle
low
low
low
upper middle
upper middle
upper middle
upper middle
low
upper middle
upper middle
low
upper middle
upper middle
lower middle
lower middle
upper middle
low
upper middle
upper middle
lower middle
lower middle
upper middle
lower middle
lower middle
low
low
upper middle
lower middle
low
upper middle
upper middle
low
low
upper middle
upper middle
lower middle
low
low
low
lo

upper middle
upper middle
low
lower middle
lower middle
low
low
lower middle
low
low
lower middle
upper middle
low
low
lower middle
low
low
upper middle
lower middle
upper middle
lower middle
low
lower middle
low
lower middle
lower middle
lower middle
lower middle
upper middle
lower middle
upper middle
low
low
lower middle
upper middle
upper middle
lower middle
lower middle
low
low
lower middle
low
low
low
low
upper middle
upper middle
low
lower middle
upper middle
upper middle
low
low
upper middle
lower middle
upper middle
upper middle
low
lower middle
upper middle
upper middle
upper middle
lower middle
lower middle
upper middle
upper middle
low
low
upper middle
low
lower middle
low
lower middle
low
upper middle
low
low
upper middle
low
low
upper middle
low
upper middle
upper middle
upper middle
low
low
low
low
low
low
upper middle
low
upper middle
lower middle
lower middle
upper middle
upper middle
lower middle
lower middle
upper middle
low
upper middle
upper middle
lower middle
lowe

low
upper middle
upper middle
lower middle
upper middle
low
low
upper middle
low
low
lower middle
upper middle
low
low
upper middle
upper middle
upper middle
upper middle
low
lower middle
lower middle
lower middle
lower middle
upper middle
low
lower middle
upper middle
low
upper middle
upper middle
upper middle
upper middle
upper middle
low
upper middle
low
low
low
low
upper middle
low
upper middle
low
low
upper middle
upper middle
lower middle
upper middle
lower middle
low
upper middle
lower middle
low
upper middle
lower middle
upper middle
low
low
upper middle
upper middle
lower middle
upper middle
low
lower middle
lower middle
low
low
upper middle
lower middle
upper middle
lower middle
upper middle
upper middle
lower middle
upper middle
low
upper middle
upper middle
upper middle
upper middle
upper middle
lower middle
upper middle
low
lower middle
upper middle
low
lower middle
upper middle
upper middle
lower middle
lower middle
lower middle
low
low
upper middle
upper middle
lower mid

In [215]:
# display first 10 rows of dataset with added column for income categorization
df.head(10)

children  days_employed  dob_years            education  education_id  \
0       1.0           8438         42    bachelor's degree             0   
1       1.0           4025         36  secondary education             1   
2       0.0           5623         33  secondary education             1   
3       3.0           4125         32  secondary education             1   
4       0.0          16060         53  secondary education             1   
5       0.0            926         27    bachelor's degree             0   
6       0.0           2879         43    bachelor's degree             0   
7       0.0            153         50  secondary education             1   
8       2.0           6930         35    bachelor's degree             0   
9       0.0           2189         41  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   
5  civil partnership                 1      M    business     0     40922.170   
6            married                 0      F    business     0     38484.156   
7            married                 0      M    employee     0     21731.829   
8  civil partnership                 1      F    employee     0     15337.093   
9            married                 0      M    employee     0     23108.150   

                               purpose age_category purpose_category  \
0                purchase of the house        40-60      residential   
1                         car purchase        20-40          vehicle   
2                purchase of the house        20-40      residential   
3              supplementary education        20-40      educational   
4                    to have a wedding        40-60            other   
5                purchase of the house        20-40      residential   
6                 housing transactions        40-60      residential   
7                            education        40-60      educational   
8                     having a wedding        20-40            other   
9  purchase of the house for my family        40-60      residential   

  income_category  
0            high  
1    lower middle  
2    lower middle  
3            high  
4    upper middle  
5            high  
6            high  
7    lower middle  
8             low  
9    lower middle

In [216]:
# count rows for each category
df['income_category'].value_counts()

low             5364
upper middle    5363
high            5363
lower middle    5363
Name: income_category, dtype: int64

Since the categorization of the data utilizes the upper bounds of the quartile ranges, the number of rows in each category is **nearly evenly distributed**, approaching one-quarter of the total entries (21,454).

[Back to Contents](#contents)

## Hypotheses

### Children and Loan Default

**Is there a correlation between having children and the likelihood of loan default?**

Column `debt` indicates the loan status of each customer. Currently the column exhibits number, with 1 representing the existance of default in the record, and 0 represents the absence of default in the record. Values in this column need to first be converted into string, where 0 is to be replaced with 'compliance' and 1 will be replaced with 'default'.

In [222]:
# change column 'debt' data type to string
df['debt'] = df['debt'].replace(0, 'compliance').replace(1, 'default')
df.head(10) #first 10 rows of dataset

children  days_employed  dob_years            education  education_id  \
0       1.0           8438         42    bachelor's degree             0   
1       1.0           4025         36  secondary education             1   
2       0.0           5623         33  secondary education             1   
3       3.0           4125         32  secondary education             1   
4       0.0          16060         53  secondary education             1   

       family_status  family_status_id gender income_type        debt  \
0            married                 0      F    employee  compliance   
1            married                 0      F    employee  compliance   
2            married                 0      M    employee  compliance   
3            married                 0      M    employee  compliance   
4  civil partnership                 1      F     retiree  compliance   

   total_income                  purpose age_category purpose_category  \
0     40620.102    purchase of the house        40-60      residential   
1     17932.802             car purchase        20-40          vehicle   
2     23341.752    purchase of the house        20-40      residential   
3     42820.568  supplementary education        20-40      educational   
4     25378.572        to have a wedding        40-60            other   

  income_category  
0            high  
1    lower middle  
2    lower middle  
3            high  
4    upper middle

Column `debt` now displays explicitely the status of a customer's loan history, where the value is either "compliance" or "default". 

The next step is to make a pivot table that exhibits the debt status (compliance or default) and the number of children. 

In [220]:
# pivot table for column 'debt' with number of child as index
child_factor = pd.pivot_table(df, index='children', columns='debt', values='income_type', aggfunc='count', margins=True)
child_factor

debt      compliance  default    All
children                            
0.0          13095.0   1071.0  14166
1.0           4410.0    445.0   4855
2.0           1858.0    194.0   2052
3.0            303.0     27.0    330
4.0             37.0      4.0     41
5.0              9.0      NaN      9
All          19712.0   1741.0  21453

Table above only display the number of customers in each debt status to the number of children that they have, but not the percentage of each debt status. The following is the calculation of percentage of each debt status:

In [223]:
# Mengitung persentase gagal bayar berdasarkan jumlah anak
child_factor['% default'] = child_factor['default'] / child_factor['All'] * 100
child_factor

debt      compliance  default    All  % default
children                                       
0.0          13095.0   1071.0  14166   7.560356
1.0           4410.0    445.0   4855   9.165808
2.0           1858.0    194.0   2052   9.454191
3.0            303.0     27.0    330   8.181818
4.0             37.0      4.0     41   9.756098
5.0              9.0      NaN      9        NaN
All          19712.0   1741.0  21453   8.115415

**Preliminary Conclusion:**

The first hypothesis posits that there is a relationship between having children and an individual's likelihood of loan default. This hypothesis is **accepted**, as a positive correlation exists between the number of children and the percentage of defaults. 

Specifically, **as the number of children increases, so does the percentage of loan defaults**.

### Family Status and Loan Default

**Is there a correlation between marital status and the likelihood of loan default?**

Similar to the testing of the first hypothesis, a pivot table is requires to display the debt status (compliance or default) and the marital status of a customer. 

In [224]:
# unique values in column family_status_id
df['family_status_id'].unique()

array([0, 1, 2, 3, 4])

In [225]:
# unique values in family_status
df['family_status'].unique()

array(['married', 'civil partnership', 'widow / widower', 'divorced',
       'unmarried'], dtype=object)

In [226]:
# pivot table for column 'debt' with 'family_status' as index
family_factor = pd.pivot_table(df, index='family_status', columns='debt', values='income_type', aggfunc='count', margins=True)
family_factor

debt               compliance  default    All
family_status                                
civil partnership        3762      388   4150
divorced                 1110       85   1195
married                 11408      931  12339
unmarried                2536      274   2810
widow / widower           896       63    959
All                     19712     1741  21453

Table above only display the number of customers in each debt status to their marital status, but not the percentage of each debt status in each family status group. The following is the calculation of percentage of each debt status:

In [227]:
# percentage of default according to family status
family_factor['% default'] = family_factor['default'] / family_factor['All'] * 100
family_factor

debt               compliance  default    All  % default
family_status                                           
civil partnership        3762      388   4150   9.349398
divorced                 1110       85   1195   7.112971
married                 11408      931  12339   7.545182
unmarried                2536      274   2810   9.750890
widow / widower           896       63    959   6.569343
All                     19712     1741  21453   8.115415

**Preliminary Conclusion:**

The second hypothesis asserts that there is a relationship between marital status and an individual's likelihood of loan default. This hypothesis is **rejected**, as the default percentages **do not exhibit a specific pattern** when comparing individuals with partners (married and in civil partnerships) to those without partners (divorced, unmarried, and widowed). 

### Income Category and Loan Default

**Is there a correlation between income level and the likelihood of loan default?**

Similar to the two previous factors (number of children and marital status), a pivot table is required to learn the distribution of people in each debt status in the categories of income. 

In [228]:
# pivot table of debt status with 'income_category' as index
income_factor = pd.pivot_table(df, index='income_category', columns='debt', values='income_type', aggfunc='count', margins=True)
income_factor

debt             compliance  default    All
income_category                            
high                   4980      383   5363
low                    4937      427   5364
lower middle           4900      463   5363
upper middle           4895      468   5363
All                   19712     1741  21453

The following table with additional column that shows percentage of default cases in each income category. 

In [231]:
# default percentage in each income category
income_factor['% default'] = income_factor['default'] / income_factor['All'] * 100
income_factor

debt             compliance  default    All  % default
income_category                                       
high                   4980      383   5363   7.141525
low                    4937      427   5364   7.960477
lower middle           4900      463   5363   8.633228
upper middle           4895      468   5363   8.726459
All                   19712     1741  21453   8.115415

**Preliminary Conclusion;**

The third hypothesis posits that there is a relationship between income level and an individual's likelihood of loan default. This hypothesis is **rejected**, as there is no evidence of a positive or negative correlation between income levels and default percentages.

### Loan Purpose and Loan Default

**How does the purpose of a loan influence the default percentage?**

In [232]:
# show default cases of each purpose category
purpose_factor = pd.pivot_table(df, index='purpose_category', columns='debt', values='income_type', aggfunc='count', margins=True)
purpose_factor

debt              compliance  default    All
purpose_category                            
educational             3643      370   4013
other                   2138      186   2324
residential            10028      782  10810
vehicle                 3903      403   4306
All                    19712     1741  21453

In [233]:
# compare default percentage across purposes
purpose_factor['% default'] = purpose_factor['default'] / purpose_factor['All'] * 100
purpose_factor

debt              compliance  default    All  % default
purpose_category                                       
educational             3643      370   4013   9.220035
other                   2138      186   2324   8.003442
residential            10028      782  10810   7.234043
vehicle                 3903      403   4306   9.359034
All                    19712     1741  21453   8.115415

**Preliminary Conclusion**

The final question addresses how loan purposes affect the likelihood of default.

The two purposes associated with the **highest default rates** are **education-related** loans and those for the **acquisition or maintenance of vehicles**. 

Conversely, the purpose with the **lowest default rate** is related to the **acquisition or maintenance of housing**.

[Back to Contents](#contents)

## Findings and Conclusions

An analysis is coducted to study factors that may affect the risk of loan default. 

In the data preprocessing stage, several issues were identified across various columns, namely:

`days_employed`
This column is intended to represent the duration of employment for each customer. However, there is no indication of the time unit used during data collection (days/months/years). There are also several missing values, and the data initially included non-integer values, with many entries reflecting negative numbers. 

These issues have been addressed by:
* Rounding the numbers and changing the data type from float to integer,
* Converting negative values to positive,
* Transforming the data into a reasonable unit of days based on the customer's age,
* Filling missing values with 0.

`children`
This column is meant to inform the number of children dependent on the customer. However, there are several entries with values that do not accurately represent this information, specifically -1 and 20. Both values have been replaced with the mean.

`dob_years`
Several entries in this column have a value of 0, which does not accurately reflect the customer's age. These zero values have been replaced with the median.

`total_income`
Missing values in this column were handled through categorization based on age. Each age category has an average income value, and the missing values within each age category have been replaced with the corresponding average.

In addition to the columns mentioned above, **data categorization** has been performed to facilitate analysis, specifically on the following columns:

`total_income`, which has now been categorized into four income levels: low, lower middle, upper middle, and high.

`purpose`, which has been categorized into four main themes: vehicle, residential, education, and others.
Duplicates in the dataset have been removed.

Ultimately, the dataframe, which initially consisted of 12 columns and 21,525 entries, now contains 14 columns and 21,454 entries, with the same number of non-null values.


**FINDINGS**
The factor that correlates with the probability of default is **the number of children**. A positive correlation exists, indicating that as the number of children increases, the percentage of defaults also rises. 

However, marital status and income level do not correlate with the probability of default, as no correlation was found between these factors and the default percentage.

Based on the purpose of the loans, the highest default probability is observed among customers with education-related loans and those for vehicle-related needs. Conversely, the lowest default probability is seen in customers with housing-related purposes.

[Back to Contents](#contents)